# ~/.tmux.conf

# set true color
# Set the default terminal program for new windows and panes inside tmux
set -g default-terminal "tmux-256color"

# Enable True Color (Tc) support and other terminal features for wezterm
set -ga terminal-overrides ",xterm-256color:RGB"

# for yazi image preveiw
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

# set prefix
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# remove confirmation
bind-key & kill-window
bind-key x kill-pane

# personal pref
set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g mode-style "bg=#45475A" # change text hightlight color


# plugin list
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'alexwforsythe/tmux-which-key'

set -g @which_key_root_table 'C-Space'

# color palette
LIGHT_BLUE=#C0CAF5
GREY=#6E738D
BLUE=#89B4FA
BLACK=#181825
BONE=#EAD7C6

# Configure Tmux
set -g status-position top
set -g status-style "bg=default"
set -g status-justify "absolute-centre"
set -g message-style "bg=default"

# appearance

# left status bar
set -g status-left-length 100
set -g status-left "\
#{?client_prefix,#[bg=default fg=${BONE}] #{session_name},#[bg=default fg=${LIGHT_BLUE}] #{session_name}}\
"
# set -g status-left "\
# #{?client_prefix,#[bg=default fg=${GREY}],#[bg=default fg=${BLUE}]}\
# #{?client_prefix,#[bg=${GREY} fg=${BLACK}]#{session_name},#[bg=${BLUE} fg=${BLACK}]#{session_name}}\
# #{?client_prefix,#[bg=default fg=${GREY}],#[bg=default fg=${BLUE}]}\
# "
set -ga status-left "#[bg=default,fg=${LIGHT_BLUE}]#{?window_zoomed_flag, | ,}"
set -ga status-left "#[bg=default,fg=${BONE}]#{?window_zoomed_flag, zoom ,}"

# right status bar
set -g status-right-length 100
set -g status-right "#[bg=default, fg=${LIGHT_BLUE}]#{host} "
# set -g status-right "\
# #[bg=default,fg=${BLUE}]\
# #[bg=${BLUE},fg=${BLACK}]#{host}\
# #[bg=default,fg=${BLUE}]\
# "
# pane border look and feel
setw -g pane-border-status top
setw -g pane-border-format ""
setw -g pane-active-border-style bg=default,fg=${LIGHT_BLUE}
setw -g pane-border-style bg=default,fg=${GREY}
setw -g pane-border-lines single

# window look and feel
set -wg automatic-rename on

set -g window-status-format "\
 \
#I:#W\
 \
"
set -g window-status-style "bg=default,fg=${LIGHT_BLUE}"
set -g window-status-last-style "bg=default,fg=${BONE}"
set -g window-status-current-format "\
#[bg=default,fg=${BLUE}]\
#[bg=${BLUE},fg=${BLACK}]#I:#W\
#[bg=default,fg=${BLUE}]\
"
set -g window-status-separator ""

# Enable a two-line status bar
# set -g status 2

# Set the first line to be blank to create a gap
# set -Fg 'status-format[1]' ''


# run tpm plugins
run '/Users/taptat/.config/tmux/plugins/tpm/tpm'
