theme = "rose_pine"

[editor]
line-number = "relative"
cursorline = true
mouse = true
color-modes = true
bufferline = "multiple" # Enable tab bar at the top
default-yank-register = "+"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# File explorer configuration
[editor.file-picker]
hidden = false
parents = false

[editor.soft-wrap]
enable = true

[keys.insert]
j = { k = "normal_mode" }

[editor.indent-guides]
render = false
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

# LSP Server configuration
[editor.lsp]
display-messages = true
auto-signature-help	= true
display-signature-help-docs	= true
